version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm start
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm start
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
